import json
import os
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from backend.shelter_allocator import allocate_shelters
from backend.alert_system import check_threshold, run_threshold_on_villages


# --------------------------------------------------
# ENVIRONMENT CONFIGURATION
# --------------------------------------------------

load_dotenv()

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173"
)


# --------------------------------------------------
# APP INITIALIZATION
# --------------------------------------------------

app = FastAPI(
    title="RELOC8 API",
    description="Backend for the RELOC8 disaster risk and relocation system",
    version="1.0.0"
)


# --------------------------------------------------
# CORS CONFIGURATION
# --------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_URL],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------------------------------------------
# PATHS & DIRECTORIES
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "datab"
FRONTEND_DATA_DIR = BASE_DIR.parent / "src" / "data"


# --------------------------------------------------
# DATA LOADING WITH ERROR HANDLING
# --------------------------------------------------

try:
    with open(DATA_DIR / "villages.json", "r", encoding="utf-8") as f:
        villages_data = json.load(f)

    print("Successfully loaded villages.json")

except Exception as e:
    print(f"Warning: Could not load villages.json: {e}")
    villages_data = []


try:
    with open(DATA_DIR / "shelters.json", "r", encoding="utf-8") as f:
        shelters_data = json.load(f)

    print("Successfully loaded shelters.json")

except Exception as e:
    print(f"Warning: Could not load shelters.json: {e}")
    shelters_data = []


try:
    with open(FRONTEND_DATA_DIR / "animals.json", "r", encoding="utf-8") as f:
        animals_data = json.load(f)

    print("Successfully loaded animals.json")

except Exception as e:
    print(f"Warning: Could not load animals.json: {e}")
    animals_data = []


try:
    with open(DATA_DIR / "alerts_data.json", "r", encoding="utf-8") as f:
        notifications_data = json.load(f)

    print("Successfully loaded alerts_data.json")

except Exception as e:
    print(f"Warning: Could not load alerts_data.json: {e}")
    notifications_data = []


# --------------------------------------------------
# IN-MEMORY DATABASES
# --------------------------------------------------

reports_db = []

# Live alerts generated by the automated threshold checker
live_alerts_db: list = []


# --------------------------------------------------
# PYDANTIC MODELS
# --------------------------------------------------

class IncidentReport(BaseModel):
    type: str
    village: str
    affectedCount: int
    description: Optional[str] = ""


class ThresholdInput(BaseModel):
    village: Optional[str] = None
    location: Optional[str] = None
    district: Optional[str] = ""
    risk_level: Optional[str] = None
    risk_score: Optional[float] = None
    water_level_m: Optional[float] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    type: Optional[str] = "Flood Warning"
    source: Optional[str] = "manual"
    message: Optional[str] = None


class NotificationCreate(BaseModel):
    title: str
    message: str
    type: Optional[str] = "General"
    severity: Optional[str] = "MEDIUM"
    district: Optional[str] = ""
    village: Optional[str] = ""
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    source: Optional[str] = "System"


# --------------------------------------------------
# ENDPOINTS: SYSTEM & CORE DATA
# --------------------------------------------------

@app.get("/")
def home():
    return {
        "message": "RELOC8 Backend is running"
    }


@app.get("/villages")
def get_villages():
    return {
        "villages": villages_data
    }


@app.get("/shelters")
def get_shelters():
    return {
        "shelters": shelters_data
    }


@app.get("/animals")
def get_animals():
    return {
        "animals": animals_data
    }


# --------------------------------------------------
# ENDPOINTS: HAZARDS & RISK ANALYSIS
# --------------------------------------------------

@app.get("/hazards")
def get_hazards():

    hazards = []

    v_list = (
        villages_data.get("villages", villages_data)
        if isinstance(villages_data, dict)
        else villages_data
    )

    for village in v_list:

        hazards.append({
            "village": village.get("village"),
            "district": village.get("district"),
            "hazard_score": village.get("hazard_score"),
            "flood_history": village.get("flood_history"),
            "risk_level": village.get("risk_level")
        })

    return {
        "hazards": hazards
    }


@app.get("/risk")
def get_risk():

    v_list = (
        villages_data.get("villages", villages_data)
        if isinstance(villages_data, dict)
        else villages_data
    )

    if not v_list:
        return {
            "risk_level": "UNKNOWN",
            "risk_score": 0,
            "affected_population": 0
        }

    highest_risk_village = max(
        v_list,
        key=lambda village: village.get("risk_score", 0)
    )

    return {
        "risk_level": highest_risk_village.get("risk_level"),
        "risk_score": highest_risk_village.get("risk_score"),
        "affected_population": highest_risk_village.get("population"),
        "village": highest_risk_village.get("village")
    }


# --------------------------------------------------
# XAI RISK SCORING
# --------------------------------------------------

def compute_xai_risk_breakdown(village_name: str):

    v_list = (
        villages_data.get("villages", villages_data)
        if isinstance(villages_data, dict)
        else villages_data
    )

    village = next(
        (
            v for v in v_list
            if v.get("village", "").lower() == village_name.lower()
        ),
        None
    )

    if not village:
        return None

    # --------------------------------------------------
    # EXISTING DATA
    # --------------------------------------------------

    population = float(
        village.get("population", 0)
    )

    rainfall = float(
        village.get("rainfall_mm", 0)
    )

    hazard_score = float(
        village.get("hazard_score", 0)
    )

    # --------------------------------------------------
    # NORMALIZED FACTOR SCORES
    # All factors are converted to a 0-100 scale.
    # --------------------------------------------------

    # Water-level / flood hazard indicator
    # Since the current dataset does not contain
    # water_level directly, hazard_score is used
    # as the available flood-risk indicator.
    water_level_score = max(
        0,
        min(100, hazard_score)
    )

    # Population score
    # 1000 people = 100 score.
    population_score = max(
        0,
        min(100, population / 10)
    )

    # Rainfall score
    # 200 mm rainfall is treated as the 100-point
    # reference level.
    rainfall_score = max(
        0,
        min(100, (rainfall / 200) * 100)
    )

    # --------------------------------------------------
    # WEIGHTED RISK CALCULATION
    #
    # Water Level        = 40%
    # Population Density = 30%
    # Weather/Rainfall   = 30%
    # --------------------------------------------------

    water_contribution = water_level_score * 0.40

    population_contribution = population_score * 0.30

    weather_contribution = rainfall_score * 0.30

    total_score = (
        water_contribution
        + population_contribution
        + weather_contribution
    )

    # --------------------------------------------------
    # RISK LEVEL
    # --------------------------------------------------

    if total_score >= 81:
        risk_level = "CRITICAL"

    elif total_score >= 61:
        risk_level = "HIGH"

    elif total_score >= 31:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    # --------------------------------------------------
    # XAI RESPONSE
    # --------------------------------------------------

    return {
        "village": village.get("village"),

        "district": village.get(
            "district",
            "Unknown"
        ),

        "predicted_risk_score": round(
            total_score,
            1
        ),

        "risk_level": risk_level,

        "xai_feature_contributions": [

            {
                "feature": "Water Level",

                "weight": 40,

                "score": round(
                    water_level_score,
                    1
                ),

                "contribution": round(
                    water_contribution,
                    1
                ),

                "reason": (
                    f"Flood hazard score is {water_level_score:.1f}/100. "
                    "This factor has the highest weight (40%) because "
                    "water-related flood conditions strongly influence "
                    "evacuation risk."
                )
            },

            {
                "feature": "Population Density",

                "weight": 30,

                "score": round(
                    population_score,
                    1
                ),

                "contribution": round(
                    population_contribution,
                    1
                ),

                "reason": (
                    f"Population score is {population_score:.1f}/100 "
                    f"based on {int(population)} people. "
                    "Higher population increases evacuation demand "
                    "and resource requirements."
                )
            },

            {
                "feature": "Weather Forecast / Rainfall",

                "weight": 30,

                "score": round(
                    rainfall_score,
                    1
                ),

                "contribution": round(
                    weather_contribution,
                    1
                ),

                "reason": (
                    f"Rainfall score is {rainfall_score:.1f}/100 "
                    f"based on {rainfall:.1f} mm rainfall. "
                    "Higher rainfall can increase flood-related risk "
                    "and evacuation urgency."
                )
            }
        ],

        "model_metadata": {

            "algorithm": (
                "Weighted Explainable Risk Scoring"
            ),

            "weights": {

                "water_level": "40%",

                "population_density": "30%",

                "weather_forecast_rainfall": "30%"
            },

            "version": "2.0.0"
        }
    }


# --------------------------------------------------
# XAI API ENDPOINT
# --------------------------------------------------

@app.get("/api/xai-risk/{village_name}")
def get_xai_risk(village_name: str):

    result = compute_xai_risk_breakdown(
        village_name
    )

    if not result:
        raise HTTPException(
            status_code=404,
            detail="Village record not found for XAI processing."
        )

    return result


# --------------------------------------------------
# ENDPOINTS: INCIDENT REPORTS
# --------------------------------------------------

@app.post("/api/reports")
def submit_report(report: IncidentReport):

    report_dict = (
        report.model_dump()
        if hasattr(report, "model_dump")
        else report.dict()
    )

    report_dict["id"] = len(reports_db) + 1

    reports_db.append(
        report_dict
    )

    return {
        "status": "success",
        "data": report_dict
    }


@app.get("/api/reports")
def get_reports():

    return {
        "reports": reports_db
    }


# --------------------------------------------------
# ENDPOINTS: ALLOCATION
# --------------------------------------------------

@app.get("/api/relocation-plan")
def get_relocation_plan():

    plan = allocate_shelters(
        villages_data,
        shelters_data
    )

    return {
        "status": "success",
        "plan": plan
    }


# --------------------------------------------------
# ENDPOINTS: AUTOMATED ALERT SYSTEM
# --------------------------------------------------

@app.post("/api/alerts/check")
def api_check_threshold(payload: ThresholdInput):
    """
    Threshold Checker endpoint.

    Send risk/water data and receive whether an alert
    should fire along with the generated alert object.
    """

    data = (
        payload.model_dump()
        if hasattr(payload, "model_dump")
        else payload.dict()
    )

    result = check_threshold(data)

    if result["alert"] and result["alert_object"]:
        live_alerts_db.insert(
            0,
            result["alert_object"]
        )

    return {
        "status": "success",
        "alert": result["alert"],
        "risk_level": result["risk_level"],
        "data": result["alert_object"]
    }


@app.post("/api/alerts/scan-villages")
def api_scan_villages():
    """
    Scan all loaded villages and generate alerts
    for HIGH or CRITICAL risk.
    """

    v_list = (
        villages_data.get("villages", villages_data)
        if isinstance(villages_data, dict)
        else villages_data
    )

    generated = run_threshold_on_villages(
        v_list or []
    )

    for alert in generated:
        live_alerts_db.insert(
            0,
            alert
        )

    return {
        "status": "success",
        "generated_count": len(generated),
        "alerts": generated
    }


# --------------------------------------------------
# ENDPOINTS: NOTIFICATIONS
# --------------------------------------------------

@app.get("/api/notifications")
def get_notifications():
    """
    Return static file alerts + live generated alerts.
    Frontend can poll this for realtime pop-ups.
    """

    static = (
        notifications_data
        if isinstance(notifications_data, list)
        else []
    )

    combined = (
        list(live_alerts_db)
        + list(static)
    )

    return {
        "notifications": combined,
        "live_count": len(live_alerts_db),
        "static_count": len(static)
    }


@app.post("/api/notifications")
def create_notification(
    note: NotificationCreate
):
    """
    Manually store a notification.
    """

    from datetime import datetime

    item = (
        note.model_dump()
        if hasattr(note, "model_dump")
        else note.dict()
    )

    item["id"] = (
        f"NOTIF-{len(live_alerts_db) + 1}"
    )

    item["issued_at"] = (
        datetime.utcnow().isoformat() + "Z"
    )

    item["status"] = "Active"

    item["alert"] = (
        item.get("severity", "").upper()
        in {"CRITICAL", "HIGH"}
    )

    live_alerts_db.insert(
        0,
        item
    )

    return {
        "status": "success",
        "data": item
    }